#!/bin/sh

for keyparams in q797n55m25kc1a q977n61m28kc2 q1409n87m42kc4 q1789n111m55kc5 q1789n111m55kc6
do
    for sigseclevel in sb80 sb96 sb112git sb112 sc1 sc1a sc2 sc3 sc4 sc5 sc6
    do
	for symalg in shake256
	do
	    echo "${keyparams} ${sigseclevel} ${symalg}"
	    ./out/test/generate-test-vectors "${keyparams}${sigseclevel}${symalg}s"
	done
    done
done
